# Blog settings
defaults:
  # Blog
  - scope:
      path: "_posts/blog"
      type: posts
    values:
      permalink: blog/:title
      category: blog
  # News
  - scope:
      path: "_posts/news"
      type: posts
    values:
      permalink: news/:year/:month/:day/:title
      category: news
  # Projects
  - scope:
      path: "_posts/projects"
      type: posts
    values:
      permalink: projects/:title
      category: projects


# My variables
name: Konstantinos Gavriil
description: Personal website of Konstantinos Gavriil
google_verification: null
baseurl: ''


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass

plugins:
  - jekyll-redirect-from

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Google services
google_analytics: UA-96352346-1
google_analytics_4: G-1L0ZGWRTJ5

# Comment section toggle
comments: true

# 'jekyll-maps'
gems:
    - jekyll-maps
    - jekyll-sitemap

maps:
    google:
        api_key: AIzaSyAcamkPPvTSfNngi8q41SuMqMGHjFCagm0
