# Blog settings
permalink: /blog/:title


# My variables
name: Konstantinos Gavriil
description: Personal website of Konstantinos Gavriil
google_verification: null
baseurl: ''


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Google services
google_analytics: UA-96352346-1

# Comment section toggle
comments: true

# 'jekyll-maps'
gems:
    - jekyll-maps
    - jekyll-sitemap

maps:
    google:
        api_key: AIzaSyAcamkPPvTSfNngi8q41SuMqMGHjFCagm0